# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='timestamp',
        ),
    ]
